# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/v1/classification.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'common/v1/classification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x63ommon/v1/classification.proto\x12\tcommon.v1\x1a google/protobuf/descriptor.proto*\xde\x01\n\x12\x44\x61taClassification\x12#\n\x1f\x44\x41TA_CLASSIFICATION_UNSPECIFIED\x10\x00\x12\x1c\n\x18\x44\x41TA_CLASSIFICATION_SAFE\x10\x01\x12\"\n\x1e\x44\x41TA_CLASSIFICATION_IDENTIFIER\x10\x02\x12\x1c\n\x18\x44\x41TA_CLASSIFICATION_PATH\x10\x03\x12\x1f\n\x1b\x44\x41TA_CLASSIFICATION_CONTENT\x10\x04\x12\"\n\x1e\x44\x41TA_CLASSIFICATION_CREDENTIAL\x10\x05:f\n\x0e\x63lassification\x12\x1d.google.protobuf.FieldOptions\x18\xc0\x8e\x03 \x01(\x0e\x32\x1d.common.v1.DataClassificationR\x0e\x63lassificationB7Z5github.com/evalops/platform/gen/go/common/v1;commonv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.v1.classification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/evalops/platform/gen/go/common/v1;commonv1'
  _globals['_DATACLASSIFICATION']._serialized_start=80
  _globals['_DATACLASSIFICATION']._serialized_end=302
# @@protoc_insertion_point(module_scope)
